### ISSUE TITLE
jsonrpc2 not correclty implemented in responses 

### ISSUE THREAD

**Issue by raffaelespazzoli** [open-iscsi/targetd#18]
based on my tests targetd does not return the field "jsonrpc": "2.0" in the response.
This is required per 
http://www.jsonrpc.org/specification
https://www.simple-is-better.org/json-rpc/transport_http.html

**Comment by tasleson** [comment]
Corrected with https://github.com/open-iscsi/targetd/pull/21

**Comment by tasleson** [comment]
Fix merged
