### ISSUE TITLE
Implement ZFS copy

### ISSUE THREAD

**Issue by tasleson** [open-iscsi/targetd#47]
Initial implementation of ZFS back-end is missing copy functionality.

ref. https://github.com/open-iscsi/targetd/blob/master/targetd/backends/zfs.py#L261

**Comment by tasleson** [comment]
@triluch Would you be willing to tackle this?

**Comment by triluch** [comment]
@tasleson sure, now that ZFS is merged, I will take a look at implementing copy.

**Comment by tasleson** [comment]
@triluch Thank you!

**Comment by tasleson** [comment]
Resolved with https://github.com/open-iscsi/targetd/pull/48
