### ISSUE TITLE
is there official pre-build Docker image?

### ISSUE THREAD

**Issue by whywaita** [open-iscsi/targetd#50]
Hi, commiters! :)

Do you have a Docker image [1] before the official build, or do you have any plans?

[1]: Example: https://hub.docker.com/r/open-iscsi/targetd

I can build a docker image, but I would like to use the official build.
I can't trust the unofficial build images. ;-

**Comment by tasleson** [comment]
New release: https://github.com/open-iscsi/targetd/releases/tag/v0.8.12

At the moment I have no plan to create docker images, but that may change in the future.

**Comment by whywaita** [comment]
OK, please think about it in the future!
