### ISSUE TITLE
Support volume resizing

### ISSUE THREAD

**Issue by johanfleury** [open-iscsi/targetd#80]
Hey

I’m currently writing a storage provisioner for Kubernetes and I found out there are no easy way to resize a volume in targetd.

What do you think about adding a new API call (something like `vol_resize(pool, vol, size)`)?

This is supported by both LVM (through [`bd_lvm_lvresize`](http://storaged.org/libblockdev/libblockdev-LVM.html#bd-lvm-lvresize)) and ZFS (by running `zfs set volsize=<size> <zpool>/<vol>`) and I can probably provide a PR if that proposal is accepted.

**Comment by tasleson** [comment]
@johanfleury This would be a fine thing to add.  When working on a PR please consider some of the same ideas that were discussed when copying a volume: https://github.com/open-iscsi/targetd/pull/78#pullrequestreview-574651567

Specifically:
1. Can you grow and shrink or just grow
2. How to handle units of size change with the various backends

**Comment by tasleson** [comment]
Implemented with https://github.com/open-iscsi/targetd/pull/81
